# Generated by Django 4.2.17 on 2025-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='const_price',
            new_name='cost_price',
        ),
    ]
